### ISSUE TITLE
SConstruct in master branch

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/PUMGen#24]
Dear All,

In the documentation, there is a way to compile with a scons, but there is no SConstruct in the main folder of master branch. Is this scons depreciated?

Thank you.

Best, 
Kadek

**Comment by krenzland** [comment]
Yup. Only cmake is supported.

**Comment by palgunadi1993** [comment]
Noted. Thank you @krenzland .

**Comment by Thomas-Ulrich** [comment]
removed
