### ISSUE TITLE
Compilation error with GMSH support

### ISSUE THREAD

**Issue by git-taufiq** [SeisSol/PUMGen#25]
Describe the issue:
Compiling pumgen (current master:https://github.com/SeisSol/PUMGen/commit/498ab011e6b4b633089fa6cd9de80205c182cd3d) with 
set(CMAKE_CXX_STANDARD 17) in CMakeLists.txt give CMake error: 

> Target "cmTC_9516a" requires the language dialect "CXX17" , but CMake does not know the compile flags to use to enable it.

then I tried changing CMakeLists.txt to  set(CMAKE_CXX_STANDARD 11) removed previous CMake error and lead to another error:

> PUMGen/src/third_party/GMSHLexer.h(49): error: "auto" function requires a trailing return type
      auto getIdentifier() const { return identifier; }
> PUMGen/src/third_party/GMSHLexer.h(50): error: "auto" function requires a trailing return type
      auto getInteger() const { return integer; }
> PUMGen/src/third_party/GMSHLexer.h(51): error: "auto" function requires a trailing return type
      auto getReal() const { return real; }
> PUMGen/src/third_party/GMSHLexer.h(52): error: "auto" function requires a trailing return type
      auto getSourceLoc() const { return loc; }
> PUMGen/src/third_party/GMSHParser.h(8): catastrophic error: cannot open source file "optional"
  #include <optional>

I tried to exclude all related to GMSH from
a) on CMakeLists.txt:
> ${CMAKE_CURRENT_SOURCE_DIR}/src/meshreader/ParallelGMSHReader.cpp
> ${CMAKE_CURRENT_SOURCE_DIR}/src/third_party/GMSHLexer.cpp
> ${CMAKE_CURRENT_SOURCE_DIR}/src/third_party/GMSHParser.cpp

b) on src/pumgen.cpp:
> #include "meshreader/ParallelGMSHReader.h"

remove "msh2":
> const char* source[] = {"gambit", "fidap", "msh2", "netcdf", "apf", "simmodsuite"};
 
and remove "case 2" and modify other case numbers according number in case list:
>         case 2:
>            logInfo(rank) << "Using GMSH mesh format 2 (msh2) mesh";
>            meshInput = new SerialMeshFile<puml::ParallelGMSHReader>(inputFile);
>            break;

with this, pumgen compiled successfully.

To Reproduce:
intel/2017
mpi.intel/2017
cmake/3.10.3
> cmake .. -DCMAKE_PREFIX_PATH=$pumiDir -DSIMMETRIX=ON \
    -DSIMMETRIX_ROOT=$simmetrixDir -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=mpiicc \ 
    -DCMAKE_CXX_COMPILER=mpiicpc
> make -j 4

**Comment by sebwolf-de** [comment]
Good morning, can you try with newer versions of cmake  (3.14.4) and intel (2019)?

**Comment by uphoffc** [comment]
Your compiler is too old. You can use an older version if you don't need gmsh.
