### ISSUE TITLE
additional dependencies have been found in case of  compilation with intel compiler

### ISSUE THREAD

**Issue by ravil-mobile** [SeisSol/PUMGen#4]
Hi all, 

So, I was installing PUMGen on my local machine using intel compiler. I found there were similar issues before, for example (from Thomas):
...
H5.c:(.text+0xcb): undefined reference to `__intel_sse2_strlen'
H5.c:(.text+0x11c): undefined reference to `__intel_sse2_strlen'
H5.c:(.text+0x190): undefined reference to `__intel_sse2_strlen'
H5.c:(.text+0x1e1): undefined reference to `__intel_sse2_strlen'
H5.c:(.text+0x27c): undefined reference to `__intel_sse2_strlen'
...

So, I found where the problem was in my case. Basically, a declaration of two libs was missed in SConscript file, namely: **irc, svml**. Maybe gcc compiler is able to find these libs for itself using the standard lookup paths but intel cannot. I added two lines two SConstruct file:
env.Append(LIBPATH=['<_path to my intel installation_>/compilers_and_libraries/linux/lib/intel64/'])
env.Append(LIBS=['irc', 'svml']), and I managed to compile PUMGen after that. Basically, hdf5 is looking for these two libs

**Comment by uphoffc** [comment]
Hi,

the error you describe is commonly seen when the Intel compiler is used to compile hdf5 and gcc is used to compile pumgen. Basically, the Intel compiler replaces some standard functions by built-in optimized functions, which lie in specific Intel libraries you describe.

So I would not see this is a bug related to PUMGen. Could you maybe check with which compiler your hdf5 was compiled?

Regards,
Carsten
