### ISSUE TITLE
PUMGEN fails with msh2, floating point exception

### ISSUE THREAD

**Issue by jrekoske** [SeisSol/PUMGen#47]
I get the following error when running pumgen with this command using a gmsh version 2 file.

`pumgen t4.msh2 -s msh2`

`Tue Aug 02 20:04:58, Info:  Using GMSH mesh format 2 (msh2) mesh`
`Tue Aug 02 20:04:58, Info:  Create APF connectivity`
`Tue Aug 02 20:04:58, Info:  Set coordinates in APF`
`Floating point exception (core dumped)`

I attached the msh2 file which should be a valid file (renamed with .txt to allow upload to Github). I generated this file with the Gmsh Python package.

[t4.txt](https://github.com/SeisSol/PUMGen/files/9244728/t4.txt)

I use the pumgen executable here: `/hppfs/work/pr63qo/di73yeq4/myLibs/PUMGen/build/pumgen` on SuperMUC-NG.

**Comment by jrekoske** [comment]
Hi, I have resolved this by creating a "PhysicalVolume" from the mesh box. It would be better if PUMGEN could give a more helpful error message here.

**Comment by sebwolf-de** [comment]
Thanks for reporting, there was indeed a missing feature hidden quite deep in the GMSH Parser.
