### ISSUE TITLE
gmsh2.2 mesh generated on windows cannot be converted

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/PUMGen#54]
Hi,

I'm collaborating with a windows user and he generated a mesh  with gmsh 4.9.? for me.
The mesh cannot be converted with pumgen, which gets stuck.
When generating the mesh on linux, the mesh can easily be converted.
Attached are the geo file and the 2 msh files (we changed the mesh sizes to have a lower cell count).

```
(base) ulrich@exception:/export/dump/ulrich$ pumgen -s msh2 ExtendedBottom_SeisSol-small_ubuntu.msh 
Wed Mar 15 14:46:49, Info:  Using GMSH mesh format 2 (msh2) mesh 
Wed Mar 15 14:46:49, Info:  Create APF connectivity 
Wed Mar 15 14:46:49, Info:  Set coordinates in APF 
Wed Mar 15 14:46:49, Info:  Mesh size: 22913 
Wed Mar 15 14:46:49, Info:  Minimum insphere found: 0.529276 
Wed Mar 15 14:46:49, Info:  Writing cells 
Wed Mar 15 14:46:49, Info:  Writing vertices 
Wed Mar 15 14:46:49, Info:  Writing group information 
Wed Mar 15 14:46:49, Info:  Writing boundary condition 
Wed Mar 15 14:46:49, Info:  Writing XDMF file 
Wed Mar 15 14:46:49, Info:  Finished successfully 

(base) ulrich@exception:/export/dump/ulrich$ pumgen -s msh2 ExtendedBottom_SeisSol-small_windows.msh 
Wed Mar 15 14:46:57, Info:  Using GMSH mesh format 2 (msh2) mesh 
```
[ExtendedBottom_SeisSol-small.zip](https://github.com/SeisSol/PUMGen/files/10980498/ExtendedBottom_SeisSol-small.zip)

**Comment by krenzland** [comment]
The short answer probably is: We do not support windows. No developer is using Windows.

(Slightly longer answer: Windows Subsystem for Linux works well)

What exactly is the difference between both files? Only line breaks (common difference between Linux/Windows)? This would be easy to fix
