### ISSUE TITLE
Pumgen smooth specific faces

### ISSUE THREAD

**Issue by jwjeremy** [SeisSol/PUMGen#55]
The current pumgen mesh attributes xml has an option of 
[`<SurfaceMeshing SmoothingLevel="3" SmoothingType="Gradient" DiscreteAngle="1.0" Snap="0"/>`](https://github.com/SeisSol/PUMGen/blob/master/XmlExample/meshAttributes.xml)

Would it be able to specify faces to smooth instead of smoothing all the surfaces in the mesh? 

It would be useful to create the complex geometry in most of the subduction zone.

**Comment by Thomas-Ulrich** [comment]
Faces are not smoothed. A smoothing algorithm on the 2D mesh is applied, replacing the nodes of the mesh (trying to get a higher quality mesh). So probably it is not what you are looking for?

**Comment by jwjeremy** [comment]
I see! Thanks for the clarification! Is there any efficient way to smooth the intersection between faces? I tried some functions in simmodeler but didn't quite work out.

**Comment by Thomas-Ulrich** [comment]
You can play with the tolerance parameter when unioning. If the input surfaces are smooth and the tolerance is small, the intersected surface should remain smooth. Can you add a snapshot of the problematic intersected surface?

**Comment by jwjeremy** [comment]
![image](https://github.com/SeisSol/PUMGen/assets/44199955/8e1014e1-31e7-45af-b392-8d941b5e0898)

The intersection between the slab2.0 geometry and the extrapolated trench

**Comment by Thomas-Ulrich** [comment]
I remember you found a work-around.
