### ISSUE TITLE
Boundary conditions incorrectly set in bypass-apf branch

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/PUMGen#64]
I'm generating a mesh with
https://github.com/SeisSol/Examples/blob/master/tpv5/generating_mirror_mesh.sh
And vizualizing the BC with:
`python ~/SeisSol/Meshing/vizualizeBoundaryConditions/vizualizeBoundaryConditions.py tpv5_f200_halfdom.xdmf 0`
I get with the bypass-apf branch
![image](https://github.com/SeisSol/PUMGen/assets/13536910/6116268c-4cd8-4fb6-95c3-1fb250131219)
and the mesh64 branch
![image](https://github.com/SeisSol/PUMGen/assets/13536910/c79e7b31-1c62-49a7-b2d4-2f46c44bd181)

**Comment by davschneller** [comment]
Ok, I see where the problem may lie... I forgot a logical "or" operator (i.e. each cell gets only the boundary condition of one face set)—after that we seem to get the full boundary conditions again, at least for the test cases I had let run. The branch is updated.
