### ISSUE TITLE
compiling pumgen with spack on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by Jing-Lee-tj** [SeisSol/PUMGen#65]
I tried compiling PUMGen with spack without simmetrix on Ubuntu 22.04.2 and results in the following error:
```
 Error: ProcessError: Command exited with status 1:
    '/opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/cmake-3.27.7-3eb3cedth3wunsstvc4dxs25o2r5wqcx/bin/cmake' '-G' 'Unix Makefiles' 
```

```
  >> 15    CMake Error at /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/cmake-3.27.7-3eb3cedth3wunsstvc4dxs25o2r5wqcx/share/cmake-3.27/Modules/FindHDF5.c
           make:571 (get_target_property):
```

```
  >> 33    CMake Error at /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/cmake-3.27.7-3eb3cedth3wunsstvc4dxs25o2r5wqcx/share/cmake-3.27/Modules/FindPackag
           eHandleStandardArgs.cmake:230 (message):
     34      Could NOT find HDF5 (missing: HL) (found version "1.12.2")
```

which can be reproduced:
        ` spack install pumgen ~with_simmetrix`
by the way, This worked a while ago, but why doesn't it work now.

**Comment by Thomas-Ulrich** [comment]
`spack install pumgen ~with_simmetrix ^hdf5 +hl`
should fix your problem.
It is again related to the default variants which have a very low priority in spack.
See https://github.com/spack/spack/issues/41139
@davschneller : can you confirm we really need HL in pumgen?
Then I will add it explicitely in the recipe of seissol, seissol-env and pumgen.

**Comment by Jing-Lee-tj** [comment]
Thanks, that was the problem, and I found that specifying the openmpi version worked as well.
