### ISSUE TITLE
mesh > 32e6 generated with pumgen@master or pumgen@bypass-apf failed when read by seissol

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/PUMGen#69]
```
dss/dsshome1/0F/ra75qeh2/seisNonl/SeisSol/submodules/PUML/PUML.h:1010: unsigned int PUML::PUML<Topo>::addFace(unsigned int, unsigned int) [with PUML::TopoType Topo = PUML::TETRAHEDRON]: Assertion `m_faces[lid].m_upward[1] == -1' failed.
```
Ziua, Nicolas, please give details.

**Comment by davschneller** [comment]
That error should roughly mean that a face appears more than twice in the mesh (while it shouldn't)—in other words, it wants to have three adjacent cells.

Can the mesh be displayed in Paraview? And does it work with v1.0.1?

**Comment by davschneller** [comment]
Can you try https://github.com/SeisSol/PUMGen/tree/davschneller/test-patch ?

**Comment by Thomas-Ulrich** [comment]
See e.g.
![image](https://github.com/SeisSol/PUMGen/assets/13536910/e8190ae9-46cf-45ee-9d0e-db23ea79dc25)

**Comment by davschneller** [comment]
I.e. incomplete? That would fit to the problem... (same for the size of 32e6)

**Comment by Thomas-Ulrich** [comment]
Ziua confirmed that it fixed the problem.
