### ISSUE TITLE
Failed in making Velocity aware mesh using PUMGEN

### ISSUE THREAD

**Issue by jwjeremy** [SeisSol/PUMGen#71]
**Describe the bug**
I applied the` <!-- VelocityAwareMeshing-->` in the pumgen xml but failed to generate mesh following the velocity structure (both 1D material and 3D material case. 

**Expected behavior**
Expect to see refinement on the meshing following the material file. 

**To Reproduce**
Pumgen: `/import/freenas-m-05-seissol/public2022/packages/PUMGen_sim10/build/pumgen`
Simmodeler: SimModeler 8.0 
Machine: Exception

Module loaded:
Currently Loaded Modulefiles:
```
1) mpi/2021.11                                           
 2) mpi.intel/2024                                        
 3) libpciaccess/0.17-gcc-12.2.0-foegz6x                  
 4) libiconv/1.17-gcc-12.2.0-pztn24l                      
 5) xz/5.4.1-gcc-12.2.0-beahnap                           
 6) zlib/1.2.13-gcc-12.2.0-qvwbld7                        
 7) libxml2/2.10.3-gcc-12.2.0-6g4ulfn                     
 8) ncurses/6.4-gcc-12.2.0-bt2tv43                        
 9) hwloc/2.9.1-gcc-12.2.0-wjb3zv3                        
10) numactl/2.0.14-gcc-12.2.0-62dxa76                     
11) bzip2/1.0.8-gcc-12.2.0-yn6mmdj                        
12) pigz/2.7-gcc-12.2.0-5w24zpq                           
13) zstd/1.5.5-gcc-12.2.0-d3iesv2                         
14) tar/1.34-gcc-12.2.0-344crw2                           
15) gettext/0.21.1-gcc-12.2.0-htnecfu                     
16) openssl/3.1.1-gcc-12.2.0-xydqrfk                      
17) krb5/1.20.1-gcc-12.2.0-ywylqdh                        
18) libedit/3.1-20210216-gcc-12.2.0-uybrqun               
19) libxcrypt/4.4.35-gcc-12.2.0-bnemwrw                   
20) openssh/9.3p1-gcc-12.2.0-nvgsowj                      
21) libevent/2.1.12-gcc-12.2.0-zgp5wia                    
22) pmix/4.2.3-gcc-12.2.0-ksjdukm                         
23) openmpi/4.1.5-gcc-12.2.0-ab5rikq                      
24) pkgconf/1.9.5-gcc-12.2.0-pdjoat6                      
25) hdf5/1.12.2-gcc-12.2.0-xwxzdqa                        
26) netcdf-c/4.7.4-gcc-12.2.0-5wzc2ic                     
27) asagi/1.0.1-gcc-12.2.0-xvz2l4l                        
28) gcc-runtime/12.2.0-gcc-12.2.0-v4wn2t2                 
29) impalajit/main-gcc-12.2.0-judjtis                     
30) nghttp2/1.52.0-gcc-12.2.0-x5wdgxs                     
31) curl/8.1.2-gcc-12.2.0-2s4wrx6                         
32) readline/8.2-gcc-12.2.0-ofdoevl                       
33) unzip/6.0-gcc-12.2.0-7wxq5cw                          
34) lua/5.3.2-gcc-12.2.0-zucnb2e                          
35) python/3.9.2-gcc-12.2.0-ikw34ao                       
36) yaml-cpp/0.6.2-gcc-12.2.0-adem7ot                     
37) easi/1.3.0-gcc-12.2.0-3egmupu                         
38) simmetrix-simmodsuite/17.0-220511-gcc-12.2.0-uzc6sef  
39) metis/5.1.0-gcc-12.2.0-kcvzwx3                        
40) parmetis/4.0.3-gcc-12.2.0-minbyzl                                 
41) zoltan/3.83-gcc-12.2.0-sl2xogx                        
42) pumi/2.2.7-gcc-12.2.0-jvajctp                         
43) pumgen/develop-gcc-12.2.0-dk4hwzp                     
44) intel-lm/1.0                                          
45) tbb                                                   
46) compiler-rt                                           
47) compiler                                              
48) intel/2022   
```                              

4. Provide parameter/material files.
All the files required to reproduce the error is in the directory with the main script and subdirectory
 `PUMGEN_mesh.sh`
`/import/freenas-m-05-seissol/jwcwong/Tohoku/MESH`
`/import/freenas-m-05-seissol/jwcwong/Tohoku/MESH/Tohoku_v7_JIVSM_2404_vel_aware_0.5hz_1D`

**Screenshots/Console output**
Mesh output (no refinement in the mesh) 
![image](https://github.com/SeisSol/PUMGen/assets/44199955/92d41e58-9389-4e0a-9686-26ea4fcaae1d)

**Additional context**
I have to load intel compiler and intel-lm math module to run pumgen. Would that be the case leading to the error? 
Error encounter without module load intel intel-lm
`pumgen: error while loading shared libraries: libimf.so:`

**Comment by davschneller** [comment]
Hi, do you have some terminal output available when creating the mesh with the velocity-aware option?

**Comment by jwjeremy** [comment]
Yes, i uploaded the output into `/import/freenas-m-05-seissol/jwcwong/Tohoku/MESH/PUMGEN_JIVSM_v7_15d_1500_1D_0.5Hz.log_0423`

Thanks!

**Comment by sebwolf-de** [comment]
On what machine is that?

**Comment by davschneller** [comment]
By the name, it's this one here: https://www.geophysik.uni-muenchen.de/en/research/geocomputing/facilities/exception

I had a look at the log; and it seems like the PUMgen version may be actually older than the velocity-aware meshing support (the respective log entries weren't there; but they were when running with a newer version of PUMgen on the same mesh).

**Comment by sebwolf-de** [comment]
So: please recompile the latest version of PUMGen and report, if the problem still persists.

Note, that I don't have access to this machine.

**Comment by jwjeremy** [comment]
The velocity-aware mesh attribute works with the latest pumgen! Thanks so much for the help!
