### ISSUE TITLE
Error while installing xml pumgen

### ISSUE THREAD

**Issue by palgunadi1993** [SeisSol/PUMGen#8]
Hi,

I got this error while compiling xml pumgen:

> In file included from src/pumgen.cpp:38:
> src/input/SimModSuite.h:557:12: error: no matching function for call to 'MS_setMeshSizePropagation'
>            MS_setMeshSizePropagation(meshCase,face,2,1,MeshAtt.MeshSizePropagationDistance,MeshAtt.MeshSizePropagationScalingFactor);
>            ^~~~~~~~~~~~~~~~~~~~~~~~~
> /project/k1343/palgunkh/myLibs/meshing_software/simmetrix/14.0-200424/include/MeshSim.h:149:21: note: candidate function not viable: requires 5 arguments, but 6 were provided
> Meshing_EXPORT void MS_setMeshSizePropagation(pACase cs, pGEntity gent, int closure, double distance, double sizeFactor);
>                     ^
> In file included from src/pumgen.cpp:38:
> src/input/SimModSuite.h:566:92: warning: expression result unused [-Wunused-value]
>            logInfo(PMU_rank()) << "UseDiscreteMesh; faceid, noModification:"<<*it, MeshAtt.UseDiscreteMesh_noModification;
>                                                                                    ~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/input/SimModSuite.h:631:15: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
>     while(ent = (pGEntity)PList_next(lsmallFeats,&iter)){
>           ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/input/SimModSuite.h:631:15: note: place parentheses around the assignment to silence this warning
>     while(ent = (pGEntity)PList_next(lsmallFeats,&iter)){
>               ^
>           (                                            )
> src/input/SimModSuite.h:631:15: note: use '==' to turn this assignment into an equality comparison
>     while(ent = (pGEntity)PList_next(lsmallFeats,&iter)){
>               ^
>               ==
> src/input/SimModSuite.h:642:20: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
>         while(vert = (pGVertex)PList_next(vertices,&iter2)){
>               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/input/SimModSuite.h:642:20: note: place parentheses around the assignment to silence this warning
>         while(vert = (pGVertex)PList_next(vertices,&iter2)){
>                    ^
>               (                                           )
> src/input/SimModSuite.h:642:20: note: use '==' to turn this assignment into an equality comparison
>         while(vert = (pGVertex)PList_next(vertices,&iter2)){
>                    ^
>                    ==
> src/input/SimModSuite.h:705:20: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
>         while (reg = RIter_next(reg_it)) {
>                ~~~~^~~~~~~~~~~~~~~~~~~~
> src/input/SimModSuite.h:705:20: note: place parentheses around the assignment to silence this warning
>         while (reg = RIter_next(reg_it)) {
>                    ^
>                (                       )
> src/input/SimModSuite.h:705:20: note: use '==' to turn this assignment into an equality comparison
>         while (reg = RIter_next(reg_it)) {
>                    ^
>                    ==
> src/input/SimModSuite.h:772:22: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
>     while(modelRegion=GRIter_next(modelRegions)) { // get the next model region
>           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
> src/input/SimModSuite.h:772:22: note: place parentheses around the assignment to silence this warning
>     while(modelRegion=GRIter_next(modelRegions)) { // get the next model region
>                      ^
>           (                                    )
> src/input/SimModSuite.h:772:22: note: use '==' to turn this assignment into an equality comparison
>     while(modelRegion=GRIter_next(modelRegions)) { // get the next model region
>                      ^
>                      ==
> src/input/SimModSuite.h:787:20: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
>     while(modelFace=GFIter_next(modelFaces)) { // get the next model face
>           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
> src/input/SimModSuite.h:787:20: note: place parentheses around the assignment to silence this warning
>     while(modelFace=GFIter_next(modelFaces)) { // get the next model face
>                    ^
>           (                                )
> src/input/SimModSuite.h:787:20: note: use '==' to turn this assignment into an equality comparison
>     while(modelFace=GFIter_next(modelFaces)) { // get the next model face
>                    ^
>                    ==
> src/input/SimModSuite.h:819:21: warning: unused variable 'hasnorm' [-Wunused-variable]
>                 int hasnorm = SimPolygons_pointData(poly, polypoint[k], pntlocation, pntnormal);
>                     ^
> src/input/SimModSuite.h:761:12: warning: unused variable 'edgeList' [-Wunused-variable]
>     pPList edgeList;  // Edges bounding a face
>            ^
> src/input/SimModSuite.h:762:12: warning: unused variable 'thisEdge' [-Wunused-variable]
>     pGEdge thisEdge;
>            ^
> 9 warnings and 1 error generated.
> scons: *** [build/src/pumgen.o] Error 1
> scons: building terminated because of errors.

Do I miss something?
Thank you.

Cheers,
Kadek

**Comment by Thomas-Ulrich** [comment]
yes there is a change in the interface of a function in the latest simModeler lib.
You have to set this variable when compiling pumgen:
https://github.com/SeisSol/PUMGen/blob/xml/SConstruct#L51

**Comment by palgunadi1993** [comment]
Adding "BeforeSim15=yes" to the scons compilation solved the problem
