### ISSUE TITLE
wrong boundary conditions

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/PUMGen#83]
I have the following xml:
```
<freeSurface>72</freeSurface>
<absorbing>46,98,71,82,62,59,76,85,80,44,48,57,83,73,53,77,92,69,89,65,64,67,47,97,75,66,87,60,50,68,81,45,50,90</absorbing>
<boundaryCondition tag="155">54,56,74,88,100</boundaryCondition>
<boundaryCondition tag="210">63,78,79,81</boundaryCondition>
<globalMSize value="8000.0"/>
<surfaceMSize value="500.0">54,56,74,88,100,63,78,79,81</surfaceMSize>
<gradation value="0.5"/>
<area_AspectRatio value="3"/>
<vol_AspectRatio value="6"/>
<SurfaceMeshing SmoothingLevel="1" SmoothingType="Gradient" DiscreteAngle="1.0" Snap="0"></SurfaceMeshing>
<VolumeMeshing  SmoothingLevel="1" SmoothingType="Gradient" SetOptimisation="1"></VolumeMeshing>
```
which seems correctly read by pumgen:

Fri Nov 08 16:03:02, Info:  faceBound[ 72 ] = 1 
Fri Nov 08 16:03:02, Info:  faceBound[ 46 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 98 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 71 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 82 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 62 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 59 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 76 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 85 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 80 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 44 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 48 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 57 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 83 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 73 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 53 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 77 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 92 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 69 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 89 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 65 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 64 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 67 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 47 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 97 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 75 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 66 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 87 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 60 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 50 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 68 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 81 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 45 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 50 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 90 ] = 5 
Fri Nov 08 16:03:02, Info:  faceBound[ 54 ] = 155 
Fri Nov 08 16:03:02, Info:  faceBound[ 56 ] = 155 
Fri Nov 08 16:03:02, Info:  faceBound[ 74 ] = 155 
Fri Nov 08 16:03:02, Info:  faceBound[ 88 ] = 155 
Fri Nov 08 16:03:02, Info:  faceBound[ 100 ] = 155 
Fri Nov 08 16:03:02, Info:  faceBound[ 63 ] = 210 
Fri Nov 08 16:03:02, Info:  faceBound[ 78 ] = 210 
Fri Nov 08 16:03:02, Info:  faceBound[ 79 ] = 210 
Fri Nov 08 16:03:02, Info:  faceBound[ 81 ] = 210 

but I get

![image](https://github.com/user-attachments/assets/0d82d4eb-59dd-464b-a164-49bf38af89cf)

pumgen@1.1

**Comment by Thomas-Ulrich** [comment]
I've compiled 1.0.1 and got the correct boundary conditions

**Comment by davschneller** [comment]
Probably, it'll also work with `simmodeler-apf` in 1.1

**Comment by davschneller** [comment]
I.e. it's probably some bug that happened when removing APF here... Somehow. That would be my guess at least.

**Comment by Thomas-Ulrich** [comment]
I confirm that there were no 255 tags at commits 6d5c21207ed128d3903aeb1265b3b209dfb4fc96 (just before the bypass apf PR).

**Comment by davschneller** [comment]
So only the 255 tags are mis-placed here; or is the whole setup broken?

**Comment by Thomas-Ulrich** [comment]
<details>
  <summary>result of adding logInfo() << sNumber; at https://github.com/SeisSol/PUMGen/blob/ef404102bc470990ac817efdefc1fbcf40ed0d8c/src/input/SimModSuite.h#L402</summary>

(base) ulrich@exception:/export/dump/ulrich/PUMGEN_folder/Norcia$ sh run_PUMGEN.sh 
Mon Nov 11 22:17:39, Info:  No filtering enabled (contiguous storage) 
Mon Nov 11 22:17:39, Info:  Using 32-bit integer boundary type conditions, or 8 bit per face (i32). 
Mon Nov 11 22:17:39, Info:  Using SimModSuite 
Mon Nov 11 22:17:39, Info:  Loading model 
Mon Nov 11 22:17:39, Info:  Extracting cases 
Mon Nov 11 22:17:39, Info:  surface smoothing option: surfaceSmoothingLevel surfaceSmoothingType surfaceFaceRotationLimit Snap 1   1   1   0 
Mon Nov 11 22:17:39, Info:  volume smoothing option: volumeSmoothingLevel volumeSmoothingType 1   1 
Mon Nov 11 22:17:39, Info:  Setting cases 
Mon Nov 11 22:17:39, Info:  faceBound[ 12 ] = 1 
Mon Nov 11 22:17:39, Info:  faceBound[ 10 ] = 5 
Mon Nov 11 22:17:39, Info:  faceBound[ 11 ] = 5 
Mon Nov 11 22:17:39, Info:  faceBound[ 13 ] = 5 
Mon Nov 11 22:17:39, Info:  faceBound[ 15 ] = 5 
Mon Nov 11 22:17:39, Info:  faceBound[ 16 ] = 5 
Mon Nov 11 22:17:39, Info:  faceBound[ 14 ] = 155 
Mon Nov 11 22:17:39, Info:  faceBound[ 17 ] = 210 
Mon Nov 11 22:17:39, Info:  globalMSize = 8000 
Mon Nov 11 22:17:39, Info:  face id: 14 , MSize = 500 
Mon Nov 11 22:17:39, Info:  face id: 17 , MSize = 500 
Mon Nov 11 22:17:39, Info:  Gradation rate = 0.8 
Mon Nov 11 22:17:39, Info:  Target equivolume AspectRatio = 6 
Mon Nov 11 22:17:39, Info:  Target equiarea AspectRatio = 3 
Mon Nov 11 22:17:39, Info:  Starting the surface mesher 
Mon Nov 11 22:17:39, Info:  Progress: Surface Meshing 
Mon Nov 11 22:17:39, Info:  Progress: Adapting Mesh 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 0 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 1 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 2 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 3 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 4 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 5 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 6 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 7 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 8 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , done 
Mon Nov 11 22:17:39, Info:  Progress: Adapting Mesh 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 0 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 1 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 2 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 3 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 4 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 5 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 6 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 7 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , 8 / 8 
Mon Nov 11 22:17:39, Info:  Progress: Face Meshing , done 
Mon Nov 11 22:17:39, Info:  Progress: Surface Mesh Improver 
Mon Nov 11 22:17:39, Info:  Progress: Surface Mesh Improvement , 0 / 1 
Mon Nov 11 22:17:39, Info:  Progress: Surface Mesh Improvement , 1 / 1 
Mon Nov 11 22:17:39, Info:  Progress: Surface Mesh Improvement , done 
Mon Nov 11 22:17:39, Info:  Progress: Surface Smoothing , 0 / 100 
Mon Nov 11 22:17:39, Info:  Progress: Surface Smoothing , done 
Mon Nov 11 22:17:39, Info:  Progress: Fix Surface Intersections 
Mon Nov 11 22:17:39, Info:  Starting the volume mesher 
Mon Nov 11 22:17:39, Info:  Progress: Volume Meshing 
Mon Nov 11 22:17:39, Info:  Progress: Creating volume mesh 
Mon Nov 11 22:17:42, Info:  Progress: Adapting Mesh 
Mon Nov 11 22:17:45, Info:  Progress: Volume Mesh Improver 
Mon Nov 11 22:17:45, Info:  Progress: Volume Optimization 
Mon Nov 11 22:17:46, Info:  Progress: Volume Smoothing , 0 / 100 
Mon Nov 11 22:17:46, Info:  Progress: Volume Smoothing , 5 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 10 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 15 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 20 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 25 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 30 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 35 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 40 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 45 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 50 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 55 / 100 
Mon Nov 11 22:17:47, Info:  Progress: Volume Smoothing , 60 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 65 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 70 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 75 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 80 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 85 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 90 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , 95 / 100 
Mon Nov 11 22:17:48, Info:  Progress: Volume Smoothing , done 
Mon Nov 11 22:17:48, Info:  AR statistics: 
Mon Nov 11 22:17:48, Info:  AR max: 6 
Mon Nov 11 22:17:48, Info:  AR (target: < ~10): 
Mon Nov 11 22:17:48, Info:    [ 0.00 , 2.00 ): 2052 
Mon Nov 11 22:17:48, Info:    [ 2.00 , 4.00 ): 79111 
Mon Nov 11 22:17:48, Info:    [ 4.00 , 6.00 ): 22729 
Mon Nov 11 22:17:48, Info:    [ 6.00 , 10.00 ): 213 
Mon Nov 11 22:17:48, Info:    [ 10.00 , 20.00 ): 0 
Mon Nov 11 22:17:48, Info:    [ 20.00 , 40.00 ): 0 
Mon Nov 11 22:17:48, Info:    [ 40.00 , 100.00 ): 0 
Mon Nov 11 22:17:48, Info:    [ 100.00 ,inf): 0 
Mon Nov 11 22:17:48, Info:  Iterating over mesh to get data... 
Mon Nov 11 22:17:48, Info:  Counting part 0 / 1 
Mon Nov 11 22:17:48, Info:  Local cells: 104105 
Mon Nov 11 22:17:48, Info:  Local vertices: 19271 
Mon Nov 11 22:17:48, Info:  Local vertices (with duplicates): 19271 
Mon Nov 11 22:17:48, Info:  Processing part 0 / 1 
Mon Nov 11 22:17:48, Info:  Vertices: 0 to 19271 
Mon Nov 11 22:17:48, Info:  Local vertices (after filtering): 19271 
Mon Nov 11 22:17:48, Info:  Processing part 0 / 1 
Mon Nov 11 22:17:48, Info:  Connectivity: 0 to 104105 
Mon Nov 11 22:17:48, Info:  Groups 
Mon Nov 11 22:17:48, Info:  Boundaries 
Mon Nov 11 22:17:48, Info:  "000000005" 
Mon Nov 11 22:17:48, Info:  "000000005" 
Mon Nov 11 22:17:48, Info:  "000000001" 
Mon Nov 11 22:17:48, Info:  "000000005" 
Mon Nov 11 22:17:48, Info:  "000000155" 
Mon Nov 11 22:17:48, Info:  "000000005" 
Mon Nov 11 22:17:48, Info:  "000000005" 
Mon Nov 11 22:17:48, Info:  "000000210" 
Mon Nov 11 22:17:48, Info:  Parsed mesh successfully, writing output... 
Mon Nov 11 22:17:48, Info:  Total cell count: 104105 
Mon Nov 11 22:17:48, Info:  Total vertex count: 19271 
Mon Nov 11 22:17:48, Info:  Minimum insphere found: 39.6523 
Mon Nov 11 22:17:48, Info:  Writing cells 
Mon Nov 11 22:17:48, Info:  Writing vertices 
Mon Nov 11 22:17:48, Info:  Writing group information 
Mon Nov 11 22:17:48, Info:  Writing boundary condition 
Mon Nov 11 22:17:48, Info:  Writing XDMF file 
Mon Nov 11 22:17:48, Info:  Finished successfully

**Comment by Thomas-Ulrich** [comment]
Example of a faulty mesh:
https://syncandshare.lrz.de/getlink/fi5jkP6ev8fEBwisxFMV3X/

**Comment by davschneller** [comment]
Thanks; both of these narrow down the problem by a lot. I may know now why; roughly at least.

If you replace the `int64_t` in https://github.com/SeisSol/PUMGen/blob/ef404102bc470990ac817efdefc1fbcf40ed0d8c/src/input/MeshData.h#L67C60-L67C77 by an `int32_t`, does the problem still occur?

EDIT: you'll also need to exchange it here: https://github.com/SeisSol/PUMGen/blob/ef404102bc470990ac817efdefc1fbcf40ed0d8c/src/input/MeshData.h#L52

**Comment by davschneller** [comment]
I was able to reproduce the bug on a small testing mesh.

(just take any gmsh file and set all boundary faces to e.g. 310; as 100 will get subtracted there)

**Comment by davschneller** [comment]
It was a casting problem. Somehow, Hdf5 keeps the sign of integers when truncating them.
